name: Universal Compilation
on:
  workflow_call:
jobs:
  UniversalLinux:
    name: Linux
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install GCC 15
        uses: egor-tensin/setup-gcc@a2861a8b8538f49cf2850980acccf6b05a1b2ae4 # v2.0
        with:
          version: 15

      - name: Download SDE package
        uses: petarpetrovt/setup-sde@d230e06df0ca06ced70000e4a7fa62afc9a2001e # v4.0
        with:
          environmentVariableName: SDE_DIR
          sdeVersion: 9.58.0

      - name: Build universal binary
        run: make -j4 -C src ARCH=x86-64-universal profile-build RUN_PREFIX="$SDE_DIR/sde -future --"

      - name: Strip binary
        run: strip src/stockfish

      - name: Rename binary
        run: mv src/stockfish stockfish-linux-x86-64-universal

      - name: Extract the bench number from the commit history
        run: |
          for hash in $(git rev-list -100 HEAD); do
            benchref=$(git show -s $hash | tac | grep -m 1 -o -x '[[:space:]]*\b[Bb]ench[ :]\+[1-9][0-9]\{5,7\}\b[[:space:]]*' | sed 's/[^0-9]//g') && break || true
          done
          [[ -n "$benchref" ]] && echo "benchref=$benchref" >> $GITHUB_ENV && echo "From commit: $hash" && echo "Reference bench: $benchref" || echo "No bench found"

      - name: Check arch selection under SDE
        run: ./scripts/check_universal.sh ./stockfish-linux-x86-64-universal "$SDE_DIR/sde" "$benchref"

      - name: Remove non src files
        run: |
          rm -fR src/temp_builds
          git -C src clean -fx

      - name: Upload artifact for (pre)-release
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: linux x86-64-universal
          path: |
             .
             !.git
             !.output

  UniversalWindows:
    name: Windows
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup msys and install required packages
        uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c # v2.31.1
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-gcc make git zip

      - name: Download SDE package
        uses: petarpetrovt/setup-sde@d230e06df0ca06ced70000e4a7fa62afc9a2001e # v4.0
        with:
          environmentVariableName: SDE_DIR
          sdeVersion: 9.58.0

      - name: Build universal binary
        run: |
          SDE_PATH=$(cygpath "$SDE_DIR")
          make -j4 -C src ARCH=x86-64-universal profile-build RUN_PREFIX="$SDE_PATH/sde.exe -future --"

      - name: Strip binary
        run: strip src/stockfish.exe

      - name: Rename binary
        run: mv src/stockfish.exe stockfish-windows-x86-64-universal.exe

      - name: Extract the bench number from the commit history
        run: |
          for hash in $(git rev-list -100 HEAD); do
            benchref=$(git show -s $hash | tac | grep -m 1 -o -x '[[:space:]]*\b[Bb]ench[ :]\+[1-9][0-9]\{5,7\}\b[[:space:]]*' | sed 's/[^0-9]//g') && break || true
          done
          [[ -n "$benchref" ]] && echo "benchref=$benchref" >> $GITHUB_ENV && echo "From commit: $hash" && echo "Reference bench: $benchref" || echo "No bench found"

      - name: Check arch selection under SDE
        run: ./scripts/check_universal.sh ./stockfish-windows-x86-64-universal.exe "$SDE_DIR/sde" "$benchref"

      - name: Remove non src files
        run: |
          rm -fR src/temp_builds
          git -C src clean -fx

      - name: Upload artifact for (pre)-release
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows x86-64-universal
          path: |
             .
             !.git
             !.output
